//Registro e inicio de sesion
export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO';
export const REGISTRO_ERROR = 'REGISTRO_ERROR';
export const OBTENER_USUARIO = 'OBTENER_USUARIO';
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const CERRAR_SESION = 'CERRAR_SESION';


//Alertas
export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';

//Evento
export const AGREGAR_EVENTO='AGREGAR_EVENTO';
export const VALIDAR_EVENTO='VALIDAR_EVENTO';
export const OBTENER_EVENTOS='OBTENER_EVENTOS';
export const ACTUALIZAR_EVENTO='ACTUALIZAR_EVENTO';
export const ELIMINAR_EVENTO='ELIMINAR_EVENTO';
export const EVENTO_ERROR = 'EVENTO_ERROR';
export const EVENTO_ACTUAL = 'EVENTO_ACTUAL'


export const OBTENER_EVENTOS2='OBTENER_EVENTOS2';
export const EVENTO_ACTUAL2 = 'EVENTO_ACTUAL2'
export const NOMINADOS_EVENTO2 = 'NOMINADOS_EVENTO2'


export const NOMINADO_NUEVO = 'NOMINADO_NUEVO'
export const CAMBIAR_ESTADO = 'CAMBIAR_ESTADO'
export const RESET_VALORES = 'RESET_VALORES'

//Nominado
export const NOMINADOS_EVENTO = 'NOMINADOS_EVENTO'
export const AGREGAR_NOMINADO = 'AGREGAR_NOMINADO'
export const VALIDAR_NOMINADO = 'VALIDAR_NOMINADO'
export const ELIMINAR_NOMINADO = 'ELIMINAR_NOMINADO'
export const ACTUALIZAR_NOMINADO = 'ACTUALIZAR_NOMINADO'
export const NOMINADO_ACTUAL = 'NOMINADO_ACTUAL'
export const CAMBIAR_ESTADO2 = 'CAMBIAR_ESTADO2'
export const OBTENER_USUARIOS = 'OBTENER_USUARIOS'

//Voto
export const AGREGAR_VOTO = 'AGREGAR_VOTO'
export const ACTUALIZAR_NOMINADO2 = 'ACTUALIZAR_NOMINADO2'
export const VERIFICAR = 'VERIFICAR'

//Grafica
export const OBTENER_GRAFICA = 'OBTENER_GRAFICA'



